### PR TITLE
Replace node:fetch with native node fetch

### PR DESCRIPTION
**Pull request by katayama8000**

### CODE REVIEW

**Comment by katayama8000** [comment]
Can not set httpAgent?

**Review by nicknovitski — CHANGES_REQUESTED** [review]
Thank you for this!  I think it's a good idea, but it will also require removing `fetch-mock` and using [undici's built-in mock features](https://undici.nodejs.org/#/docs/best-practices/mocking-request) instead.

**Comment by douglowder** [comment]
@nicknovitski `fetch-mock` is now removed, I merged your PR #98

**Comment by katayama8000** [comment]
I switched the branch because fixing the conflicts is difficult.

**Comment by douglowder** [comment]
Closing this in favor of newer PR #116

**Pull request closed without merging**
