### PR TITLE
Fix error when run `npm run watch`

### PR DESCRIPTION
**Pull request by katayama8000**

### CODE REVIEW

**Comment by katayama8000** [comment]
Could you review this PR? @ide

**Comment by ide** [comment]
I will take a look a little over a week from now after React Conf and App.js Conf wrap up. Thank you for understanding.

**Comment by katayama8000** [comment]
Sure!
Have a nice conf ide.

**Comment by ide** [comment]
Hi - would you still like me to review this or do you not need this change anymore?

**Comment by katayama8000** [comment]
I closed this PR accidentaly.
I made new one. So Can you review it?
https://github.com/expo/expo-server-sdk-node/pull/70

**Pull request closed without merging**
